site_name: "SOSóptica"

theme:
  #logo: assets/logo/logo.png
  #favicon: assets/logo/logo.png
  name: material
  language: "pt"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Sobre: index.md
  - Visão do produto e projeto: visao.md
  - Sprints:
      - Sprint 1: Sprint1.md
      - Sprint 2: Sprint2.md
      - Sprint 3: Sprint3.md
      - Sprint 4: Sprint4.md
  - Entregas:
      - Unidade 1: Entrega1.md
      - Unidade 2: Entrega2.md
      - Unidade 3: Entrega3.md
  - Backlog do Produto: BacklogDoProduto.md
  - Canvas MVP: CanvasMVP.md
  - Pontuação do MVP: pontuação-dos-mvps.md
